# mkinitcpio.conf for Aero Linux
# Btrfs + LUKS + resume support

MODULES=(btrfs crc32c libcrc32c sr_mod cdrom ata_piix ahci)
BINARIES=(/usr/bin/btrfsck)
FILES=()
HOOKS=(base udev autodetect microcode modconf kms keyboard keymap consolefont block encrypt archiso btrfs filesystems fsck)
COMPRESSION="zstd"
COMPRESSION_OPTIONS=(-T0 -19)