# Aero Linux - Window rules

# Ghostty
windowrulev2 = float, class:^(ghostty)$, title:^(Float)$

# Firefox / Chromium
windowrulev2 = opacity 1.0 override 0.9 override, class:^(firefox|chromium)$

# GTK file picker
windowrulev2 = float, title:^(File Upload|File picker|Choose file)$
windowrulev2 = size 800 600, title:^(File Upload|File picker|Choose file)$

# Imv (image viewer)
windowrulev2 = float, class:^(imv)$

# Mpv
windowrulev2 = float, class:^(mpv)$

# Pseudo-transparency for terminals
windowrulev2 = opacity 0.95 override 0.9 override, class:^(ghostty)$

# Pin wlogout
windowrulev2 = pin, class:^(wlogout)$
windowrulev2 = nofocus, class:^(wlogout)$
windowrulev2 = fullscreen, class:^(wlogout)$

# Pin walker
windowrulev2 = pin, class:^(walker)$
windowrulev2 = nofocus, class:^(walker)$

# Lockscreen
windowrulev2 = fullscreen, class:^(hyprlock)$
windowrulev2 = noanim, class:^(hyprlock)$
