# Aero Linux - Window rules

# Ghostty
windowrule = float on, match:class ^(ghostty)$, match:title ^(Float)$

# Firefox / Chromium
windowrule = opacity 1.0 override 0.9 override, match:class ^(firefox|chromium)$

# GTK file picker
windowrule = float on, match:title ^(File Upload|File picker|Choose file)$
windowrule = size 800 600, match:title ^(File Upload|File picker|Choose file)$

# Imv (image viewer)
windowrule = float on, match:class ^(imv)$

# Mpv
windowrule = float on, match:class ^(mpv)$

# Pseudo-transparency for terminals
windowrule = opacity 0.95 override 0.9 override, match:class ^(ghostty)$

# Pin wlogout
windowrule = pin on, match:class ^(wlogout)$
windowrule = no_focus on, match:class ^(wlogout)$
windowrule = fullscreen on, match:class ^(wlogout)$

# Pin walker
windowrule = pin on, match:class ^(walker)$
windowrule = no_focus on, match:class ^(walker)$

# Lockscreen
windowrule = fullscreen on, match:class ^(hyprlock)$
windowrule = no_anim on, match:class ^(hyprlock)$
