# Global zsh environment for Aero Linux
export ZDOTDIR="${HOME}/.config/zsh"
export XDG_CONFIG_HOME="${HOME}/.config"
export XDG_DATA_HOME="${HOME}/.local/share"
export XDG_STATE_HOME="${HOME}/.local/state"
export XDG_CACHE_HOME="${HOME}/.cache"

# Default applications
export EDITOR="nvim"
export VISUAL="nvim"
export TERMINAL="ghostty"
export BROWSER="firefox"
export PAGER="bat"
export MANPAGER="sh -c 'col -bx | bat -l man -p'"

# Path additions
export PATH="${HOME}/.local/bin:${PATH}"

# Zsh history
export HISTFILE="${ZDOTDIR}/.zsh_history"
export HISTSIZE=10000
export SAVEHIST=10000